# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - odin-pdf-container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://odintestregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_0cf87a3a9a794047ae9734b046d559de }}
        password: ${{ secrets.AzureAppService_ContainerPassword_349f17d2891b46ff91856b4aff87ade6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: odintestregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0cf87a3a9a794047ae9734b046d559de }}/nestpdf-ssh:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'odin-pdf-container'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cd2c06e7ae59435c88807e15ec5489db }}
        images: 'odintestregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0cf87a3a9a794047ae9734b046d559de }}/nestpdf-ssh:${{ github.sha }}'